"""Entrypoint and subcommands for carrion-spine CLI."""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path
from typing import NoReturn


def main() -> None:
    """Console script entrypoint."""
    parser = argparse.ArgumentParser(
        prog="carrion-spine",
        description="Carrion: Spine — Discord-first config control plane for 7 Days to Die",
    )
    parser.add_argument(
        "--config",
        "--path",
        dest="config_path",
        type=Path,
        default=Path("config.toml"),
        help="Path to config.toml (default: config.toml)",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # init
    init_p = subparsers.add_parser("init", help="Create config.toml and .env.example interactively")
    init_p.add_argument("--path", type=Path, default=Path("config.toml"), help="Write config to this path")
    init_p.set_defaults(func=_cmd_init)

    # doctor
    doc_p = subparsers.add_parser("doctor", help="Check roots, backup dir, SQLite path; warn about Discord setup")
    doc_p.add_argument("--config", type=Path, default=Path("config.toml"), help="Config file path")
    doc_p.set_defaults(func=_cmd_doctor)

    # run
    run_p = subparsers.add_parser("run", help="Run Spine bot using config and DISCORD_TOKEN")
    run_p.add_argument("--config", type=Path, default=Path("config.toml"), help="Config file path")
    run_p.set_defaults(func=_cmd_run)

    # install-systemd
    sys_p = subparsers.add_parser(
        "install-systemd",
        help="Generate systemd unit and tmpfiles.d snippet for production",
    )
    sys_p.add_argument("--user", default="carrion", help="Service user (default: carrion)")
    sys_p.add_argument("--group", default="carrion", help="Service group (default: carrion)")
    sys_p.add_argument("--config", type=Path, default=Path("/etc/carrion-spine/config.toml"), help="Config path in deployed env")
    sys_p.add_argument("--workdir", type=Path, default=None, help="Working directory (default: derived from config)")
    sys_p.set_defaults(func=_cmd_install_systemd)

    args = parser.parse_args()
    fn = getattr(args, "func", None)
    if fn is None:
        parser.print_help()
        sys.exit(0)
    fn(args)


def _cmd_init(args: argparse.Namespace) -> None:
    """Interactive init: prompt for settings, write config.toml and .env.example."""
    config_path = getattr(args, "path", args.config_path)
    config_path = Path(config_path).resolve()

    print("Carrion: Spine — Config setup")
    print("Leave blank to use default or skip. You can edit config.toml later.\n")

    token_prompt = "Bot token (or env var name, e.g. DISCORD_TOKEN) [DISCORD_TOKEN]: "
    token_input = input(token_prompt).strip() or "DISCORD_TOKEN"

    roots_prompt = "Config roots (absolute paths, comma-separated) [e.g. /srv/7dtd]: "
    roots_input = input(roots_prompt).strip() or "/srv/7dtd"

    backup_prompt = "Backup directory [backups]: "
    backup_input = input(backup_prompt).strip() or "backups"

    roles_prompt = "Module access role IDs (Discord role IDs, comma-separated) []: "
    roles_input = input(roles_prompt).strip()

    # Optional file profile roles skipped for brevity; user can edit TOML
    roots_list = [r.strip() for r in roots_input.split(",") if r.strip()]
    roles_list = [x.strip() for x in roles_input.split(",") if x.strip()]
    role_ids = []
    for r in roles_list:
        try:
            role_ids.append(int(r))
        except ValueError:
            pass

    lines = [
        "# Carrion: Spine config",
        "# Generated by: carrion-spine init",
        "",
        "[spine]",
        "# Token from env: set DISCORD_TOKEN or the variable you entered above",
        "data_dir = \"data\"",
        f"backup_dir = \"{backup_input}\"",
        "backup_keep = 10",
        "max_upload_bytes = 5242880",
        "",
        "config_roots = [",
    ]
    for r in roots_list:
        lines.append(f'    "{r}",')
    lines.append("]")
    lines.append("")
    lines.append("module_access_roles = [")
    for rid in role_ids:
        lines.append(f"    {rid},")
    lines.append("]")
    lines.append("")
    lines.append("# Optional: file_profile_roles = { \"serverconfig.xml\" = [123, 456] }")

    toml_content = "\n".join(lines)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(toml_content, encoding="utf-8")
    print(f"Wrote: {config_path}")

    env_name = token_input if token_input.isupper() or token_input.startswith("DISCORD") else "DISCORD_TOKEN"
    env_example = f"# Copy to .env and set your bot token\n# Never commit .env\n{env_name}=your_bot_token_here\n"
    env_path = config_path.parent / ".env.example"
    env_path.write_text(env_example, encoding="utf-8")
    print(f"Wrote: {env_path}")
    print("Next: set your token in .env (or export DISCORD_TOKEN), then run: carrion-spine doctor && carrion-spine run")


def _cmd_doctor(args: argparse.Namespace) -> None:
    """Check config, roots, backup dir, SQLite path; warn about Discord."""
    config_path = getattr(args, "config", args.config_path)
    config_path = Path(config_path).resolve()

    try:
        from carrion_spine.config_loader import load_config
        loaded = load_config(config_path)
    except FileNotFoundError:
        print("Config file not found:", config_path)
        print("Run: carrion-spine init")
        sys.exit(2)
    except Exception as e:
        print("Config error:", e)
        sys.exit(2)

    critical = 0

    # Roots exist and RW
    for root in loaded.roots:
        p = root.path
        if not p.exists():
            print(f"  Roots: {p} does not exist")
            critical += 1
        elif not p.is_dir():
            print(f"  Roots: {p} is not a directory")
            critical += 1
        else:
            try:
                (p / ".spine_check").write_text("")
                (p / ".spine_check").unlink()
            except OSError as e:
                print(f"  Roots: {p} not writable: {e}")
                critical += 1
            else:
                print(f"  Roots: {p} exists and is RW")

    # Backup dir
    try:
        loaded.backup_dir.mkdir(parents=True, exist_ok=True)
        (loaded.backup_dir / ".spine_check").write_text("")
        (loaded.backup_dir / ".spine_check").unlink()
        print(f"  Backup dir: {loaded.backup_dir} OK")
    except OSError as e:
        print(f"  Backup dir: {loaded.backup_dir} — cannot create or write: {e}")
        critical += 1

    # SQLite path
    try:
        loaded.data_dir.mkdir(parents=True, exist_ok=True)
        if loaded.sqlite_path.exists():
            loaded.sqlite_path.touch()
        else:
            loaded.sqlite_path.write_text("")
            loaded.sqlite_path.unlink()
        print(f"  SQLite path: {loaded.sqlite_path} writable")
    except OSError as e:
        print(f"  SQLite path: {loaded.sqlite_path} — not writable: {e}")
        critical += 1

    # Discord
    token = os.environ.get("DISCORD_TOKEN") or os.environ.get("CARRION_SPINE_TOKEN")
    if not token or token == "your_bot_token_here":
        print("  Discord: DISCORD_TOKEN not set or placeholder — set it before run")
    else:
        print("  Discord: token env set")

    print("  Discord: ensure bot has Message Content Intent and can read/write in channels where you run /mm")

    if critical:
        sys.exit(1)
    print("All critical checks passed.")


def _cmd_run(args: argparse.Namespace) -> None:
    """Run bot using config; token from DISCORD_TOKEN or config env var name."""
    config_path = getattr(args, "config", args.config_path)
    config_path = Path(config_path).resolve()
    if not config_path.is_file():
        print("Config not found:", config_path, file=sys.stderr)
        sys.exit(2)

    os.environ["CARRION_SPINE_CONFIG"] = str(config_path)
    token = os.environ.get("DISCORD_TOKEN") or os.environ.get("CARRION_SPINE_TOKEN")
    if not token or token == "your_bot_token_here":
        print("Set DISCORD_TOKEN (or CARRION_SPINE_TOKEN) before running.", file=sys.stderr)
        sys.exit(2)

    try:
        from carrion_spine.config_loader import load_config
        load_config(config_path)
    except Exception as e:
        print("Config error:", e, file=sys.stderr)
        sys.exit(2)

    asyncio.run(_run_bot(token))


def _cmd_install_systemd(args: argparse.Namespace) -> None:
    """Generate systemd unit file and tmpfiles.d snippet."""
    user = getattr(args, "user", "carrion")
    group = getattr(args, "group", "carrion")
    config_path = getattr(args, "config", Path("/etc/carrion-spine/config.toml"))
    workdir = getattr(args, "workdir", None)
    config_path = Path(config_path).resolve()
    if workdir is None:
        workdir = config_path.parent

    unit = f"""[Unit]
Description=Carrion Spine Discord Bot Module Host
After=network.target

[Service]
Type=simple
User={user}
Group={group}
WorkingDirectory={workdir}
Environment="PYTHONUNBUFFERED=1"
EnvironmentFile=-/etc/carrion-spine/env
Environment="CARRION_SPINE_CONFIG={config_path}"
ExecStart=/usr/bin/carrion-spine run --config {config_path}
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths={workdir} /var/backups/carrion_spine

[Install]
WantedBy=multi-user.target
"""
    tmpfiles = f"""# Carrion Spine data dirs (adjust paths to match config.toml)
d /var/lib/carrion-spine 0755 {user} {group} -
d /var/lib/carrion-spine/data 0755 {user} {group} -
d /var/backups/carrion_spine 0755 {user} {group} -
"""
    print("Generated systemd unit. Save to /etc/systemd/system/carrion-spine.service:")
    print(unit)
    print("\nGenerated tmpfiles.d snippet. Save to /etc/tmpfiles.d/carrion-spine.conf:")
    print(tmpfiles)
    print("Then run:")
    print("  sudo systemctl daemon-reload")
    print("  sudo systemctl enable carrion-spine")
    print("  sudo systemctl start carrion-spine")


async def _run_bot(token: str) -> None:
    """Run a minimal Discord bot that loads only carrion_spine.commands."""
    import discord
    from discord.ext import commands

    intents = discord.Intents.default()
    intents.message_content = True
    bot = commands.Bot(command_prefix="!", intents=intents)

    @bot.event
    async def on_ready() -> None:
        print("Carrion: Spine bot online. Use /mm in Discord.")

    async def start() -> None:
        async with bot:
            await bot.load_extension("carrion_spine.commands")
            await bot.start(token)

    await start()
